/**
 * Shared type definitions for the db-video-editor 4K rendering engine.
 *
 * The composition model is intentionally simple and serializable so that the
 * same description can be (a) executed in the main thread, (b) shipped to a
 * worker thread pool for concurrent rendering, and (c) generated by an AI
 * director from a natural-language prompt.
 */
import type { SKRSContext2D } from '@napi-rs/canvas';

/** Default prop bag used when a composition does not declare a stricter type. */
export type DefaultProps = Record<string, unknown>;

/**
 * The pure mathematical scene function required by the composition framework.
 *
 * A scene is fully described by this single function: given a 2D context that
 * has already been initialised at the target resolution, the current frame
 * index, the frame rate and a serialisable prop bag, it draws exactly one
 * frame. It must be deterministic and side-effect free apart from drawing.
 *
 * Dimensions and the current time can always be derived:
 *   const { width, height } = ctx.canvas;
 *   const t = frame / fps;
 */
export type RenderFrame<Props = DefaultProps> = (
  ctx: SKRSContext2D,
  frame: number,
  fps: number,
  props: Props,
) => void;

/** A single audio track to be muxed into the final output. */
export interface AudioTrack {
  /** Path to the audio file. Relative paths resolve against the assets root. */
  path: string;
  /** Offset in seconds into the final timeline where this track begins. */
  startAt?: number;
  /** Linear gain, 0..1 (defaults to 1). */
  volume?: number;
}

/** Canonical resolution presets. */
export interface Resolution {
  width: number;
  height: number;
}

/** 4K UHD. */
export const UHD_4K: Resolution = { width: 3840, height: 2160 };
/** Full HD. */
export const FHD_1080: Resolution = { width: 1920, height: 1080 };
/** HD. */
export const HD_720: Resolution = { width: 1280, height: 720 };

/**
 * A registered, renderable composition.
 *
 * `renderFrame` is the scene function; `defaultProps` are merged with any
 * caller-supplied props before rendering so scenes always receive a complete
 * prop object.
 */
export interface Composition<Props = DefaultProps> {
  id: string;
  width: number;
  height: number;
  fps: number;
  durationInSeconds: number;
  /** Asset paths (images / fonts / audio) referenced by this composition. */
  assets?: string[];
  /** Audio tracks mixed into the final output when this composition is used. */
  audio?: AudioTrack[];
  /** Default values for any props the scene reads. */
  defaultProps?: Props;
  renderFrame: RenderFrame<Props>;
}

/** A scene as authored in a project script JSON file. */
export interface SceneSpec {
  /** The registered composition id to use for this scene. */
  id: string;
  /** Duration of this scene in seconds. */
  durationInSeconds: number;
  /** Props forwarded to the scene's `renderFrame` call (merged with defaults). */
  props?: DefaultProps;
  /** Audio tracks attached to this scene; their `startAt` is scene-local. */
  audio?: AudioTrack[];
}

/** The top-level project script format consumed by `cli.ts build`. */
export interface ProjectScript {
  version?: number;
  title?: string;
  /** Output file; overridden by the CLI `--output` flag when present. */
  output?: string;
  width?: number;
  height?: number;
  fps?: number;
  /** Encoder hint: 'auto' (default) or a specific ffmpeg encoder name. */
  encoder?: string;
  /** Max worker threads (defaults to an engine-chosen value). */
  concurrency?: number;
  scenes: SceneSpec[];
}

/**
 * A fully resolved, serialisable timeline segment. This is what gets shipped to
 * worker threads: it references a composition by id and pins it to a range of
 * global frame indices.
 */
export interface SegmentSpec {
  compositionId: string;
  startFrame: number;
  frameCount: number;
  fps: number;
  props: DefaultProps;
}

/**
 * The full serialisable description of a render. Both the main thread and the
 * worker pool execute against this same structure.
 */
export interface TimelineSpec {
  width: number;
  height: number;
  fps: number;
  totalFrames: number;
  segments: SegmentSpec[];
}

/** An audio track pinned to an absolute timeline offset (post-resolution). */
export interface AudioPlan extends AudioTrack {
  startAt: number;
  volume: number;
  /** Absolute path on disk (resolved by the asset preloader). */
  absolutePath: string;
}

/** A complete render job handed to the engine. */
export interface RenderPlan {
  width: number;
  height: number;
  fps: number;
  totalFrames: number;
  timeline: TimelineSpec;
  audio: AudioPlan[];
  output: string;
}

/** Progress callback: (framesWrittenSoFar, totalFrames). */
export type ProgressFn = (frame: number, totalFrames: number) => void;

/** Options accepted by {@link render}. */
export interface RenderOptions {
  /** Override the auto-detected ffmpeg binary. */
  ffmpegPath?: string;
  /** Override the auto-detected ffprobe binary. */
  ffprobePath?: string;
  /** Encoder: 'auto', a specific encoder name, or omitted. */
  encoder?: string;
  /** Worker count; <=1 disables the worker pool (single-thread streaming). */
  concurrency?: number;
  onProgress?: ProgressFn;
}

/** Result returned by {@link render}. */
export interface RenderResult {
  outputFile: string;
  width: number;
  height: number;
  fps: number;
  totalFrames: number;
  elapsedMs: number;
  encoder: string;
  hardware: boolean;
  concurrency: number;
}
